### ISSUE TITLE
Increasing the Maximum of PGN Tags

### ISSUE THREAD

**Issue by patrickwayodi** [pointerish/pgn2fixture#1]
First of all I want to thank you for creating pgn2fixtures. My issue is that when I try to use a PGN file that has more than 16 tags, the output includes all the extra tags within the "moves" field. The same error occurs on other PGNs that have more than 16 tags. I've looked through the source code but I can't find the section where that maximum was set.

This was one of the inputs:

[Event "WCh 2018"]
[Site "London ENG"]
[Date "2018.11.09"]
[Round "1"]
[White "Caruana, Fabiano"]
[Black "Carlsen, Magnus"]
[Result "1/2-1/2"]
[WhiteTitle "GM"]
[BlackTitle "GM"]
[WhiteElo "2832"]
[BlackElo "2835"]
[ECO "B31"]
[Opening "Sicilian"]
[Variation "Nimzovich-Rossolimo attack (with ...g6, without ...d6)"]
[WhiteFideId "2020009"]
[BlackFideId "1503014"]
[EventDate "2018.11.09"]

1. e4 c5 2. Nf3 Nc6 3. Bb5 g6 4. Bxc6 1/2-1/2

This was the output:

{
    "model": "collection",
    "pk": 1,
    "fields": {
        "event": "WCh 2018",
        "site": "London ENG",
        "date": "2018.11.09",
        "round": "1",
        "white": "Caruana, Fabiano",
        "black": "Carlsen, Magnus",
        "result": "1/2-1/2",
        "whitetitle": "GM",
        "blacktitle": "GM",
        "whiteelo": "2832",
        "blackelo": "2835",
        "eco": "B31",
        "opening": "Sicilian",
        "variation": "Nimzovich-Rossolimo attack (with ...g6, without ...d6)",
        "whitefideid": "2020009",
        "blackfideid": "1503014",
        "moves": "EventDate \"2018.11.09\"]1. e4 c5 2. Nf3 Nc6 3. Bb5 g6 4. Bxc6 1/2-1/2"
    }
}

**Comment by pointerish** [comment]
Hi Patrick,

Sorry for taking so long to fix this. I just updated the code here:

https://github.com/pointerish/pgn2fixture/pull/2

I also added a Github Action workflow that updates the package in PyPI and it now has the latest version so you can install it via `pip install`

Hopefully it's still useful for you!

**Comment by patrickwayodi** [comment]
Thanks so much for the fix. Yes, it's still very useful for me. I really appreciate what you've done.
